### ISSUE TITLE
USER STORY: View Shopping Cart

### ISSUE THREAD

**Issue by AmandaB2023** [AmandaB2023/Bespoke_Equestrian#12]
As a **user** I can **view the items in my shopping cart** so that **I can decide which items I want to purchase **

**Acceptance Criteria**

- Shopping cart is displayed on the top right with a cart symbol to make it easily identifiable.
- The items the user has added to the shopping cart are displayed.
- The cart shows the title, price and  quantity for each item.
- The cart also shows the total price for the items .

**Tasks**

- [x] show shopping bag icon on top right hand side.
- [x] when user add item to bag total updates.
- [x] when icon clicked show details ,cost and quantity of item.
- [x] Have update and delete item options.
