### ISSUE TITLE
USER STORY: Checkout

### ISSUE THREAD

**Issue by AmandaB2023** [AmandaB2023/Bespoke_Equestrian#17]
As a **user** I can **got to the checkout** so that **I can purchase the items in my basket**

**Acceptance Criteria**

- The user can purchase the items in their basket by using a secure checkout page.
- The checkout page includes custom HTML.
- The checkout page will ask the user input their name , address and payment details.
- On hitting the make payment button , funds will me transferred via stripe to the the businesses account.

**Tasks**

- [x] Create custom form with required fields
- [x] Install Django countries.
- [x] Set up stripe for payments .
- [x] Add webhooks.
