### ISSUE TITLE
USER STORY: Shopping Bag Quantity

### ISSUE THREAD

**Issue by AmandaB2023** [AmandaB2023/Bespoke_Equestrian#22]
As a **user** I can **adjust the quantity of items in my bag** so that **I can purchase more or less of any item**

**Acceptance Criteria**
Be able to add more the one of the same items to shopping cart.
Be able to decrease the number of items in my shopping cart .

**Tasks**

- [x] Have a plus and minus button on the individual products page.
- [x] Show the number of each item in shopping bag 
- [x] Have an update button on the shopping back.
- [x] Have a remove button on the shopping bag
