### ISSUE TITLE
USER STORY: Create Product

### ISSUE THREAD

**Issue by AmandaB2023** [AmandaB2023/Bespoke_Equestrian#4]
As a **admin** I can **create a product** so that **it can be added to the store directory**

**Acceptance Criteria**

- A superuser can log into the admin panel and create a new product.

**Tasks**

- [x] Create products app
- [x] Add models and views 
- [x] Create product template
- [x] Install pillow for images.
- [x] Add product
