### ISSUE TITLE
USER STORY: Product Information

### ISSUE THREAD

**Issue by AmandaB2023** [AmandaB2023/Bespoke_Equestrian#9]
As a **user** I can **click on a product** so that ** I can see more information and images of the product in question**

**Acceptance Criteria**

- I can click on a product to get a more detailed view.
- I can see more information about the product including a detailed description, more images, different options available and price.
- I can also select the quantity I require. 

**Tasks**

- [x] Click on product to get more information.
- [x] Increase and decrease quantity option.
- [x] Add to shopping bag button.
